### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by KristinaRiabova** [KristinaRiabova/Decomposition_of_Course_Syllabus#4]
### Fundamentals of Project Management
- [ ] Task: Learn the fundamentals of project management
### Task Tracking Systems
- [ ] Task: Compare different task tracking systems (Jira, Azure DevOps, Trello, RedMine, etc.)
### Risk & Change Management
- [ ] Task: Study risk and change management methods
 ### Team Work Tools & Fundamentals
- [ ] Task: Understand the role of communication in teamwork
- [ ] Task: Explore tools for team collaboration
### Estimation
- [ ] Task: Learn estimation techniques
### Documentation
- [ ] Task: Understand how tests can serve as documentation
- [ ] Task: Consider the task tracker archive as a source of documentation
- [ ] Task: Consider code as documentation
- [ ] Task: Prepare technical documentation
- [ ] Task: Prepare architecture documentation
- [ ] Task: Prepare end-user documentation
- [ ] Task: Prepare project documentation
- [ ] Task: Investigate issues related to documentation
